state_size: 29
nb_actions: 3
seed: 150
exp: 'result/exp7'

Torcs:
  name: 'Torcs-v0'
  vision: false
  throttle: true
  gear_change: false
  track: 'practice.xml'

Training:
  epochs: 50000
  batch_size: 32
  loss_metrics: 'mse'
  nb_steps_warmup_critic: 100
  nb_steps_warmup_actor: 100
  nb_max_episode_steps: 10000
  weight_save_interval: 200

model:
  load_weight: 0
  actor_weight: 'result/exp4/ddpg_Torcs-v0_final_weights_actor.h5f'
  critic_weight: 'result/exp4/ddpg_Torcs-v0_final_weights_critic.h5f'
